const updates = [
  {
    version: "1.6.4",
    date: "1 January 2025",
    changes: [
      "Added a spotting system for 'infected'",
      "Enabled the monster 'vanilla' to spawn underground",
      "Fixed 'commander' and 'screamer' being able to scream again",
      "Added some blocks that are now craftable",
      "Enabled functionality for furniture chairs, allowing players to sit on them",
      "Fixed an issue where some projectiles didn't deal damage",
      "Fixed hazmat suits not emitting fluid upon death",
      "Improved NPCs to have deeper and lower-pitched voices",
      "Improved the sprinter variant",
      "Improved the spawner system",
      "Enhanced particles: blood hits, bleeding effects, and gun muzzle flashes"
    ]
  },
  {
    version: "1.6.3-2 Hotfix Update",
    date: "17 December 2024",
    changes: [
      "Added a new UI",
      "Modified player corpses to allow wearing equipment upon death",
      "Fixed NPCs attacking corpses",
      "Fixed gunner NPCs killing teammates",
      "Fixed invisible items",
      "Fixed an issue where canned tuna couldn't be opened",
      "Improved gravel textures",
      "Improved loot tables",
      "Improved the functionality of the vanilla shovel to allow burying corpses",
      "Updated the starter kit to no longer remove your equipment"
    ]
  },
  {
    version: "1.6.3-1 Hotfix Update",
    date: "13 December 2024",
    changes: [
      "Fixed invisible item icons",
    "Fixed support for Philippines & Chinese languages",
      "Fixed all medical items that previously provided no effect",
      "Removed 2 blocks (shhh...)",
      "Known bugs: Backpack cannot be repaired for the time being",
     "Known bugs: Bleeding particle appears even though you're not   bleeding (use rag/bandage)"
    ]
  },
  {
    version: "1.6.3",
    date: "10 December 2024",
    changes: [
      "Added female Scavenger",
      "Fixed firearms that had infinite ammo",
      "Fixed first aid lootables not dropping empty blood bags and tinctures",
      "Fixed NPCs that can shoot not making distance sound",
      "Fixed all guns not making distance sound",
      "Updated to version 1.21.50",
      "Updated the Fogs",
      "Updated language support",
      "Updated all spawn rules",
      "Walkie talkies can no longer be obtained in civilian lootboxes",
      "All blocks can now be exposed to water",
      "Updated spawn rules",
      "Changed the tip message to make it easier to understand",
      "Changed some block textures: ",
      " - grass block",
      " - podzol",
      " - mycelium",
      " - grass path",
      " - dirt",
      " - coarse dirt",
      " - rotted dirt",
      " - all types of sand blocks except the red one (no need to change)"
    ]
  },
  {
    version: "1.6.2",
    date: "12 November 2024",
    changes: [
      "Added Wooden stake and nail trap recipes",
      "Added new advancements",
      "Added Trade Scavs",
      "Added Chinese language",
      "Improved backpack functionality",
      "Nerfed infection time",
      "Nerfed some melee weapon durability",
      "Changed the 'Spawner' egg rate",
      "Updated some textures",
      "Nerfed vehicle health",
      "Changed paintings",
      "Updated terrain colors",
      "Fixed infection effect not clearing when using antidote",
      "Fixed Wooden Plank recipes",
      "Fixed player models",
      "Fixed bleeding particles",
      "Fixed can opener and pot issues",
      "Fixed hand movement being awkward when bobbing is active"
    ]
  },
  {
    version: "1.6.1 Hotfix Update",
    date: "28 October 2024",
    changes: [
      "Fixed Ender Chest inventory issues",
      "Fixed yellow backpack",
      "Fixed some guns having ammo reduced faster than intended",
      "Fixed broken bones message",
      "Fixed UI not translated into some languages",
      "Fixed Iron Golem behavior",
      "Fixed Scav/Mara not having equipment to wear (melee)",
      "Fixed blood bags not providing blood upon use",
      "Updated all language support and fixed some translations",
      "Removed 'View more statistics'",
      "Removed slim model player (you know the reason for this)"
    ]
  },
  {
    version: "1.6 Major Update",
    date: "27 October 2024",
    changes: [
      "Added messages for item and effects (bleeding, broken bones)",
      "Added language support for Indonesian, French, Spanish, Russian, Portuguese, and Thai",
      "Added blood types: A, AB, B, O",
      "Added more hit detection: head and legs",
      "Added backpacks: School backpack and Taloon backpack",
      "Added new animations: 3 for infected, 3 for humans/players, sprint animation for gunners",
      "Added blood system",
      "Added item and block grouping for specific types",
      "Added crosshair for guns",
      "Added bullets can break legs (5% chance)",
      "Added infected runner",
      "Added new bleeding and infection mechanisms",
      "Added drug overdose",
      "Added new noise system",
      "Added headshot death message",
      "Infected now stay near spawn point",
      "Infected despawn when difficulty is peaceful",
      "Added corpse mechanics: infected, players, and survivors can be buried or cut",
      "Added new blocks and items",
      "Added lockpick mechanism",
      "Added lore for guns",
      "Added new structures",
      "Added welcome message upon joining",
      "Added random avatar generation (hair, eyes, skin, gender) on first join",
      "Added advancements (beta version)",
      "Updated corpse despawn time (default: 5 minutes)",
      "Enabled corpse entity spawn on death (default: true)",
      "Reset player status on death (default: true)",
      "Creative mode now shows player status (default: false)",
      "Added game mode commands: !c, !s, !sp, !d, !n",
      "Added kill commands: !k, !ke, !kp, !kc",
      "Added other commands: !avatar, !status, !config, !help, !list",
      "Reduced overdose threshold from 50 to 20",
      "Increased blood level from 2500 to 3500",
      "Headshot damage now varies by firearm type",
      "Reworked infected and human code",
      "Reduced shotgun bullet hit range",
      "Changed frag grenade explosion time",
      "Grenades no longer disappear in creative mode",
      "Improved gunner behavior",
      "Moved start kit and collect water to scripts",
      "Remade icons for vests and helmets",
      "Remade some textures",
      "Renamed some items (e.g., AWM empty to L96 empty)",
      "Adjusted vehicle health",
      "Changed shotgun crosshair",
      "Revised infected spawn rules",
      "Added 54 inventory slots to player corpses",
      "Updated colormap v2",
      "Fixed gunner issues (scavenger/marauder)",
      "Fixed various block and item issues",
      "Fixed Glock 17 damage",
      "Fixed player corpse issues",
      "Fixed sedan bugs",
      "Fixed firearms with missing fire rates",
      "Fixed infected animations",
      "Fixed knight sword and sickle issues",
      "Fixed compass icons",
      "Fixed missing textures and icons for paper, crates, medical boxes, and reflective green/lime",
      "Fixed grenades and hazmat spawn egg",
      "Removed headshot damage from shotguns",
      "Removed old grenade code",
      "Removed start kit event in player.json",
      "Removed some clothes, vests, and helmets",
      "Temporarily removed player animations"
    ]
  },
  {
    version: "1.5.4",
    date: "18 June 2024",
    changes: [
      "Updated the spawner rate",
      "Fixed fog range (If still complain, I have to burn you down)",
      "Fixed Spec-ops NVG texture",
      "Fixed manifest to support scripts in 1.21",
      "Fixed all item scripts for version 1.21",
      "Removed hidden command blocks in bunkers",
      "Fixed C4 and secret items that could only be used once",
      "Removed Gunner version of Scav & Marauder (will be re-added in 1.6 or soon)"
    ]
  },
  {
    version: "1.5.3.3",
    date: "7 May 2024",
    changes: [
      "Added 1 new structure",
      "Fixed infected detection range for spotting",
      "Fixed stun grenade not causing flash effect",
      "Fixed L96A1 reload animation",
      "Fixed item scripts that didn't add additional effects",
      "Fixed stamina not draining when sprinting",
      "Fixed stamina disappearing when drinking too much alcohol",
      "Fixed bleeding particles",
      "Fixed ambient wind sound",
      "Removed vanilla water bottle that kills the player"
    ]
  },
  {
    version: "1.5.3.1 Hotfix Update",
    date: "29 April 2021",
    changes: [
      "Fixed item scripts not providing effects",
      "Fixed broken addon that prevented guns from being fired",
      "Updated desert camo boonie hat texture",
      "Updated splint recipes"
    ]
  },
  {
    version: "1.5.3",
    date: "29 April 2024",
    changes: [
      "Added more structures (+6 structures with variants)",
      "Updated can opener code",
      "Buffed and nerfed some item functions",
      "Added new desert camo",
      "Canned ham, corned beef, rations, and tuna can now be opened with a can opener or sharp melee weapons",
      "Fixed all items not working in 1.20.80 due to script issues",
      "Fixed player corpse despawning",
      "Fixed player corpses dropping items from inventory when interacting with a knife",
      "Fixed RPK recoil issues",
      "Fixed marauder and scav name tags using scripts",
      "Fixed marauder and scav spawn eggs not working",
      "Fixed infected always spotting players even when hidden behind walls",
      "Fixed hazmat suits not being fire immune",
      "Removed night vision effect from coffee",
      "Removed overpowered treasures in bunker structures"
    ]
  },
  {
    version: "1.5.2",
    date: "15 April 2024",
    changes: [
      "Added new infected aggressive sensor",
      "Updated infected behavior to no longer play spotted animations when the player shoots guns",
      "Introduced new infected noise system",
      "Nerfed/Buffed infected hazmat and commander",
      "Adjusted player corpses to stay longer before despawning",
      "Fixed screamer corpse issues",
      "Fixed projectile impact sound",
      "Fixed NVG view when aiming and shooting with snipers",
      "Fixed survivor group display names"
    ]
  },
  {
    version: "1.5.0 Major Update",
    date: "8 April 2024",
    changes: [
      "Mobs can now be buried with a shovel",
      "Added KURU effect",
      "Players can now take meat from players/human corpses",
      "Refillable water from water",
      "Added 2 miscellaneous items",
      "Added stun grenade",
      "Added useable waterpump",
      "Added explosive distance sound (only for addon)",
      "Added 6 clothing items (+6 shirts)",
      "Added C4 explosive",
      "Added 21 cosmetic items (+14 headwear, +8 vests)",
      "Added blood critical hit effect",
      "Added 3 new guns (+1 handgun, +1 shotgun, +1 AR)",
      "Added impact sounds (sound corresponds to the block)",
      "Added the ability to throw water when sneaking (ensuring safe drinking)",
      "Added Scavenger (Friendly survivor group)",
      "Added 34 new decorations (+32 props, +2 blocks)",
      "Added can opener with new cans feature",
      "Added 31 new structures",
      "Added vanilla brick variant texture",
      "Added bullet hole effect",
      "Improved ambient sound (Different biomes)",
      "Added Humvee with 10 variants",
      "Added player starter kit",
      "Added infected Screamer",
      "Added infected Commander (3 variants)",
      "Added small horde",
      "Added ammo system for survivor group (they switch to melee if guns are empty)",
      "Added 'Smart' variant infected that can break doors and glass, and open doors",
      "Rag now gives dirty rag",
      "Updated death/dead animation controller to be more accurate",
      "Updated infected (spotted, lootable corpses, more skin variants, new animations)",
      "Updated broken bone mechanic",
      "Updated explosive code",
      "Updated structure spawn rate and changes",
      "Added light block and camera shake effects to explosives",
      "Updated infected hazmat (effects and particles)",
      "Improved NVG UI (without effect)",
      "Updated rare loot drop chances",
      "Updated walkie talkie message system",
      "Updated landmines with a 50/50 chance to explode and drop items",
      "Updated bullet range for low, mid, and long ranges",
      "Added slowness effect to m1911 and ump45 (stun effect)",
      "Added some melee weapons that can stun NPCs (e.g., sledgehammer)",
      "New firearm animation + reload system",
      "Buffed infected military (health and damage)",
      "Added reload voice for marauders and scavs",
      "New firearm animation",
      "New AI for marauders and scavs",
      "Made stamina hidden",
      "The radio now has an effect when turned on with small radio details",
      "Added new male hairstyle",
      "Added more male and female hair variants",
      "Lootboxes now drop 2-3 items",
      "NPCs can now hold more guns",
      "Fixed yellow monobloc chair name",
      "Fixed infected Hazmat corpses not giving effects",
      "Fixed unobtainable frag grenades in loot",
      "Fixed gunshot sound and distance",
      "Fixed wooden barricades not being craftable",
      "Changed structures that use iron blocks to smooth stone",
      "Replaced AWM (300magnum) with L96A1 (7.62x51mm)",
      "Removed some structure light resources",
      "Removed infected survivor group (due to code limitations)",
      "Removed all NPC corpses (everything is now one entity)",
      "Removed 300magnum ammo",
      "You now need a small sharp melee weapon or can opener to open cans",
      "No hit immunity"
    ]
  },
  {
    version: "1.4 Major update",
    date: "8 December 2023",
    changes: [
      "Added 8 new guns",
      "Added detailed ammo system",
      "Added stamina bar",
      "Added 8 types of food",
      "Added 3 types of drinks",
      "Added supply drop feature",
      "Added walkie talkie (use for calling supply drop)",
      "Added 30 clothing items (Pants +7, Shirt +23)",
      "Added 34 accessories (chest +12, head +23)",
      "Added 5 new melee weapons",
      "Added 15 decorations",
      "Added 2D items for blocks",
      "Added hit sound effects",
      "Added sterilized rag (new mechanism to heal infections)",
      "Added two variants of military infected",
      "Added militia infected (Miniboss)",
      "Added tundra and desert fog",
      "Added 50 new structures (Total 90 structures)",
      "Added 5 new loot items",

      "Remade all loot block textures",
      "Replaced adrenaline and morphine with auto injectors",
      "Updated loot table",
      "Updated vehicles, retextured sedan and motorcycle",
      "Remade tracksuit texture",
      "Updated sandbag to 3D model",
      "Updated secret item",
      "Updated infected chase behavior (running when seeing target)",
      "Updated all items with command event",
      "Updated hesco block to a normal layered block",
      "Updated infected reaction to gun sounds",
      "Updated shotgun animation",
      "Updated rare loot to be lockable (requires lockpick to open)",
      "Updated block code to Minecraft version 1.20.30",
      "Updated marauder NPC: Shoot and reload animations (for variant guns), shift backwards when player approaches (Gunners only)",
      "Updated drink, food, medicine, and miscellaneous items",
      "Updated bullets can break glass",
      "Increased distance sound volume",

      "Removed military bandage",
      "Removed morphine bottle, adrenaline bottle, antidote bottle, and syringe",
      "Removed certain food items: canned stew, canned mac-n-cheese",
      "Removed riot helmet",
      "Removed marauders collecting items (to be added again soon)",

      "Fixed burndown infected civilian male",
      "Added Garand PING sound effect",
      "Fixed secret item",
      "Fixed gun jams (again)",
      "Fixed structure not spawning in Minecraft version 1.20.30"
    ]
  },
  {
    version: "1.3.3",
    date: "22 August 2023",
    changes: [
      "Fixed gun jams",
      "Replaced 1.3 reload to 1.2 reload",
      "Reduced lag",
      "Fixed firefighter structure",
      "Updated medical and firefighter loot",
      "Updated sedan and motorcycle"
    ]
  }
];

export { updates };